version: "2.2"
services:
  database:
  
    image: postgres
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - webnet  


  server:
 
    build: .\server\
    ports:
      - "8080:8080"
    networks:
      - webnet    
networks:
    webnet:
      driver: bridge