version: "3.3"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build: .\server\
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: