# Use an official Go runtime as a parent image
FROM  golang:1.16
# Set the Current Working Directory inside the container
WORKDIR /app/server
# Copy all files from the current directory to the PWD (Present Working Directory) inside the container
COPY . . 

RUN go build -o ./app/out/server .
# This container exposes port 8080 to the outside world
EXPOSE 8080
# Run the binary program produced by `go build` from out folder
CMD ["./app/out/server"]
